// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8uhVGOiym55kCk4ax8c5V9eKdFTznixE',
    appId: '1:60270770558:web:83e45d55eacc39cef4db2f',
    messagingSenderId: '60270770558',
    projectId: 'mm-muslim-support',
    authDomain: 'mm-muslim-support.firebaseapp.com',
    storageBucket: 'mm-muslim-support.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaKW0-CHWOnVZ8p43blS2OECj9k4zF6Ug',
    appId: '1:60270770558:android:46fe678dfc8310aaf4db2f',
    messagingSenderId: '60270770558',
    projectId: 'mm-muslim-support',
    storageBucket: 'mm-muslim-support.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1eGHtNe9060YzDDSxiiWG18F88P3EFtA',
    appId: '1:60270770558:ios:e0cb86da73579f4ff4db2f',
    messagingSenderId: '60270770558',
    projectId: 'mm-muslim-support',
    storageBucket: 'mm-muslim-support.firebasestorage.app',
    iosBundleId: 'com.dynaverse.mmMuslimSupport',
  );
}
