class AllahName {
  final int number;
  final String arabic;
  final String transliteration;
  final String meaning;

  const AllahName({
    required this.number,
    required this.arabic,
    required this.transliteration,
    required this.meaning,
  });
}

const List<AllahName> allahNames = [
  AllahName(number: 1, arabic: 'الرَّحْمَنُ', transliteration: 'Ar-Rahman', meaning: 'The Most Gracious'),
  AllahName(number: 2, arabic: 'الرَّحِيمُ', transliteration: 'Ar-Raheem', meaning: 'The Most Merciful'),
  AllahName(number: 3, arabic: 'الْمَلِكُ', transliteration: 'Al-Malik', meaning: 'The King'),
  AllahName(number: 4, arabic: 'الْقُدُّوسُ', transliteration: 'Al-Quddus', meaning: 'The Most Sacred'),
  AllahName(number: 5, arabic: 'السَّلاَمُ', transliteration: 'As-Salam', meaning: 'The Source of Peace'),
  AllahName(number: 6, arabic: 'الْمُؤْمِنُ', transliteration: "Al-Mu'min", meaning: 'The Granter of Security'),
  AllahName(number: 7, arabic: 'الْمُهَيْمِنُ', transliteration: 'Al-Muhaymin', meaning: 'The Overseer'),
  AllahName(number: 8, arabic: 'الْعَزِيزُ', transliteration: 'Al-Aziz', meaning: 'The Mighty'),
  AllahName(number: 9, arabic: 'الْجَبَّارُ', transliteration: 'Al-Jabbar', meaning: 'The Compeller'),
  AllahName(number: 10, arabic: 'الْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', meaning: 'The Majestic'),
  AllahName(number: 11, arabic: 'الْخَالِقُ', transliteration: 'Al-Khaliq', meaning: 'The Creator'),
  AllahName(number: 12, arabic: 'الْبَارِئُ', transliteration: "Al-Bari'", meaning: 'The Maker'),
  AllahName(number: 13, arabic: 'الْمُصَوِّرُ', transliteration: 'Al-Musawwir', meaning: 'The Fashioner'),
  AllahName(number: 14, arabic: 'الْغَفَّارُ', transliteration: 'Al-Ghaffar', meaning: 'The Oft-Forgiving'),
  AllahName(number: 15, arabic: 'الْقَهَّارُ', transliteration: 'Al-Qahhar', meaning: 'The Subduer'),
  AllahName(number: 16, arabic: 'الْوَهَّابُ', transliteration: 'Al-Wahhab', meaning: 'The Bestower'),
  AllahName(number: 17, arabic: 'الرَّزَّاقُ', transliteration: 'Ar-Razzaq', meaning: 'The Provider'),
  AllahName(number: 18, arabic: 'الْفَتَّاحُ', transliteration: 'Al-Fattah', meaning: 'The Opener'),
  AllahName(number: 19, arabic: 'الْعَلِيمُ', transliteration: "Al-'Aleem", meaning: 'The All-Knowing'),
  AllahName(number: 20, arabic: 'الْقَابِضُ', transliteration: 'Al-Qaabid', meaning: 'The Constrictor'),
  AllahName(number: 21, arabic: 'الْبَاسِطُ', transliteration: 'Al-Baasit', meaning: 'The Expander'),
  AllahName(number: 22, arabic: 'الْخَافِضُ', transliteration: 'Al-Khaafid', meaning: 'The Abaser'),
  AllahName(number: 23, arabic: 'الرَّافِعُ', transliteration: 'Ar-Rafi', meaning: 'The Exalter'),
  AllahName(number: 24, arabic: 'الْمُعِزُّ', transliteration: "Al-Mu'izz", meaning: 'The Honorer'),
  AllahName(number: 25, arabic: 'الْمُذِلُّ', transliteration: 'Al-Mudhill', meaning: 'The Dishonorer'),
  AllahName(number: 26, arabic: 'السَّمِيعُ', transliteration: 'As-Sami', meaning: 'The All-Hearing'),
  AllahName(number: 27, arabic: 'الْبَصِيرُ', transliteration: 'Al-Baseer', meaning: 'The All-Seeing'),
  AllahName(number: 28, arabic: 'الْحَكَمُ', transliteration: 'Al-Hakam', meaning: 'The Judge'),
  AllahName(number: 29, arabic: 'الْعَدْلُ', transliteration: "Al-'Adl", meaning: 'The Just'),
  AllahName(number: 30, arabic: 'اللَّطِيفُ', transliteration: 'Al-Lateef', meaning: 'The Subtle One'),
  AllahName(number: 31, arabic: 'الْخَبِيرُ', transliteration: 'Al-Khabeer', meaning: 'The All-Aware'),
  AllahName(number: 32, arabic: 'الْحَلِيمُ', transliteration: 'Al-Haleem', meaning: 'The Forbearing'),
  AllahName(number: 33, arabic: 'الْعَظِيمُ', transliteration: "Al-'Azeem", meaning: 'The Magnificent'),
  AllahName(number: 34, arabic: 'الْغَفُورُ', transliteration: 'Al-Ghafoor', meaning: 'The All-Forgiving'),
  AllahName(number: 35, arabic: 'الشَّكُورُ', transliteration: 'Ash-Shakoor', meaning: 'The Appreciative'),
  AllahName(number: 36, arabic: 'الْعَلِيُّ', transliteration: "Al-'Aliyy", meaning: 'The Most High'),
  AllahName(number: 37, arabic: 'الْكَبِيرُ', transliteration: 'Al-Kabeer', meaning: 'The Most Great'),
  AllahName(number: 38, arabic: 'الْحَفِيظُ', transliteration: 'Al-Hafeez', meaning: 'The Preserver'),
  AllahName(number: 39, arabic: 'الْمُقِيتُ', transliteration: 'Al-Muqeet', meaning: 'The Sustainer'),
  AllahName(number: 40, arabic: 'الْحَسِيبُ', transliteration: 'Al-Haseeb', meaning: 'The Reckoner'),
  AllahName(number: 41, arabic: 'الْجَلِيلُ', transliteration: 'Al-Jaleel', meaning: 'The Majestic'),
  AllahName(number: 42, arabic: 'الْكَرِيمُ', transliteration: 'Al-Kareem', meaning: 'The Generous'),
  AllahName(number: 43, arabic: 'الرَّقِيبُ', transliteration: 'Ar-Raqeeb', meaning: 'The Watchful'),
  AllahName(number: 44, arabic: 'الْمُجِيبُ', transliteration: 'Al-Mujeeb', meaning: 'The Responder'),
  AllahName(number: 45, arabic: 'الْوَاسِعُ', transliteration: 'Al-Wasi', meaning: 'The All-Encompassing'),
  AllahName(number: 46, arabic: 'الْحَكِيمُ', transliteration: 'Al-Hakeem', meaning: 'The Wise'),
  AllahName(number: 47, arabic: 'الْوَدُودُ', transliteration: 'Al-Wadud', meaning: 'The Loving'),
  AllahName(number: 48, arabic: 'الْمَجِيدُ', transliteration: 'Al-Majeed', meaning: 'The Glorious'),
  AllahName(number: 49, arabic: 'الْبَاعِثُ', transliteration: "Al-Ba'ith", meaning: 'The Resurrector'),
  AllahName(number: 50, arabic: 'الشَّهِيدُ', transliteration: 'Ash-Shaheed', meaning: 'The Witness'),
  AllahName(number: 51, arabic: 'الْحَقُّ', transliteration: 'Al-Haqq', meaning: 'The Truth'),
  AllahName(number: 52, arabic: 'الْوَكِيلُ', transliteration: 'Al-Wakeel', meaning: 'The Trustee'),
  AllahName(number: 53, arabic: 'الْقَوِيُّ', transliteration: 'Al-Qawiyy', meaning: 'The Strong'),
  AllahName(number: 54, arabic: 'الْمَتِينُ', transliteration: 'Al-Mateen', meaning: 'The Firm'),
  AllahName(number: 55, arabic: 'الْوَلِيُّ', transliteration: 'Al-Waliyy', meaning: 'The Protector'),
  AllahName(number: 56, arabic: 'الْحَمِيدُ', transliteration: 'Al-Hameed', meaning: 'The Praiseworthy'),
  AllahName(number: 57, arabic: 'الْمُحْصِي', transliteration: 'Al-Muhsi', meaning: 'The Accounter'),
  AllahName(number: 58, arabic: 'الْمُبْدِئُ', transliteration: "Al-Mubdi'", meaning: 'The Originator'),
  AllahName(number: 59, arabic: 'الْمُعِيدُ', transliteration: "Al-Mu'eed", meaning: 'The Restorer'),
  AllahName(number: 60, arabic: 'الْمُحْيِي', transliteration: 'Al-Muhyi', meaning: 'The Giver of Life'),
  AllahName(number: 61, arabic: 'الْمُمِيتُ', transliteration: 'Al-Mumeet', meaning: 'The Bringer of Death'),
  AllahName(number: 62, arabic: 'الْحَيُّ', transliteration: 'Al-Hayy', meaning: 'The Ever-Living'),
  AllahName(number: 63, arabic: 'الْقَيُّومُ', transliteration: 'Al-Qayyum', meaning: 'The Self-Subsisting'),
  AllahName(number: 64, arabic: 'الْوَاجِدُ', transliteration: 'Al-Wajid', meaning: 'The Finder'),
  AllahName(number: 65, arabic: 'الْمَاجِدُ', transliteration: 'Al-Majid', meaning: 'The Noble'),
  AllahName(number: 66, arabic: 'الْواحِدُ', transliteration: 'Al-Wahid', meaning: 'The Unique'),
  AllahName(number: 67, arabic: 'الأَحَدُ', transliteration: 'Al-Ahad', meaning: 'The One'),
  AllahName(number: 68, arabic: 'الصَّمَدُ', transliteration: 'As-Samad', meaning: 'The Eternal'),
  AllahName(number: 69, arabic: 'الْقَادِرُ', transliteration: 'Al-Qadir', meaning: 'The Able'),
  AllahName(number: 70, arabic: 'الْمُقْتَدِرُ', transliteration: 'Al-Muqtadir', meaning: 'The Powerful'),
  AllahName(number: 71, arabic: 'الْمُقَدِّمُ', transliteration: 'Al-Muqaddim', meaning: 'The Expediter'),
  AllahName(number: 72, arabic: 'الْمُؤَخِّرُ', transliteration: "Al-Mu'akhkhir", meaning: 'The Delayer'),
  AllahName(number: 73, arabic: 'الأَوَّلُ', transliteration: 'Al-Awwal', meaning: 'The First'),
  AllahName(number: 74, arabic: 'الآخِرُ', transliteration: 'Al-Akhir', meaning: 'The Last'),
  AllahName(number: 75, arabic: 'الظَّاهِرُ', transliteration: 'Az-Zahir', meaning: 'The Manifest'),
  AllahName(number: 76, arabic: 'الْبَاطِنُ', transliteration: 'Al-Batin', meaning: 'The Hidden'),
  AllahName(number: 77, arabic: 'الْوَالِي', transliteration: 'Al-Wali', meaning: 'The Governor'),
  AllahName(number: 78, arabic: 'الْمُتَعَالِي', transliteration: "Al-Muta'ali", meaning: 'The Most Exalted'),
  AllahName(number: 79, arabic: 'الْبَرُّ', transliteration: 'Al-Barr', meaning: 'The Source of Goodness'),
  AllahName(number: 80, arabic: 'التَّوَّابُ', transliteration: 'At-Tawwab', meaning: 'The Acceptor of Repentance'),
  AllahName(number: 81, arabic: 'الْمُنْتَقِمُ', transliteration: 'Al-Muntaqim', meaning: 'The Avenger'),
  AllahName(number: 82, arabic: 'الْعَفُوُّ', transliteration: "Al-'Afuww", meaning: 'The Pardoner'),
  AllahName(number: 83, arabic: 'الرَّؤُوفُ', transliteration: "Ar-Ra'uf", meaning: 'The Kind'),
  AllahName(number: 84, arabic: 'مَالِكُ الْمُلْكِ', transliteration: 'Malik-ul-Mulk', meaning: 'The Owner of All Sovereignty'),
  AllahName(number: 85, arabic: 'ذُو الْجَلاَلِ وَالإكْرَامِ', transliteration: 'Dhul-Jalali wal-Ikram', meaning: 'The Lord of Majesty and Generosity'),
  AllahName(number: 86, arabic: 'الْمُقْسِطُ', transliteration: 'Al-Muqsit', meaning: 'The Equitable'),
  AllahName(number: 87, arabic: 'الْجَامِعُ', transliteration: 'Al-Jami', meaning: 'The Gatherer'),
  AllahName(number: 88, arabic: 'الْغَنِيُّ', transliteration: 'Al-Ghaniyy', meaning: 'The Self-Sufficient'),
  AllahName(number: 89, arabic: 'الْمُغْنِي', transliteration: 'Al-Mughni', meaning: 'The Enricher'),
  AllahName(number: 90, arabic: 'الْمَانِعُ', transliteration: 'Al-Mani', meaning: 'The Preventer'),
  AllahName(number: 91, arabic: 'الضَّارُ', transliteration: 'Ad-Darr', meaning: 'The Distressor'),
  AllahName(number: 92, arabic: 'النَّافِعُ', transliteration: 'An-Nafi', meaning: 'The Benefiter'),
  AllahName(number: 93, arabic: 'النُّورُ', transliteration: 'An-Nur', meaning: 'The Light'),
  AllahName(number: 94, arabic: 'الْهَادِي', transliteration: 'Al-Hadi', meaning: 'The Guide'),
  AllahName(number: 95, arabic: 'الْبَدِيعُ', transliteration: 'Al-Badi', meaning: 'The Originator'),
  AllahName(number: 96, arabic: 'الْبَاقِي', transliteration: 'Al-Baqi', meaning: 'The Everlasting'),
  AllahName(number: 97, arabic: 'الْوَارِثُ', transliteration: 'Al-Warith', meaning: 'The Inheritor'),
  AllahName(number: 98, arabic: 'الرَّشِيدُ', transliteration: 'Ar-Rashid', meaning: 'The Righteous Teacher'),
  AllahName(number: 99, arabic: 'الصَّبُورُ', transliteration: 'As-Sabur', meaning: 'The Patient'),
];
