import 'package:mm_muslim_support/utility/constants.dart';

class QuranSongModel {
  final String name;
  final int number;
  final String mp3Url;
  final String filePath;

  const QuranSongModel({required this.name, required this.number, required this.mp3Url, required this.filePath});
}

// final List<QuranSongModel> surahList = const [
//   QuranSongModel(
//     name: 'Al-Fatiha',
//     number: 1',
//     mp3Url: '$${AppConstants.quranRecitationUrl}001.mp3',
//     filePath: '', // Local file path (e.g., after download)
//   ),
//   QuranSongModel(
//     name: 'Al-Baqarah',
//     number: 2',
//     mp3Url: '$${AppConstants.quranRecitationUrl}002.mp3',
//     filePath: '',
//   ),
//   QuranSongModel(
//     name: 'Al-Imran',
//     number: 3',
//     mp3Url: '$${AppConstants.quranRecitationUrl}003.mp3',
//     filePath: '',
//   ),
//   QuranSongModel(
//     name: 'An-Nisa',
//     number: 4',
//     mp3Url: '$${AppConstants.quranRecitationUrl}004.mp3',
//     filePath: '',
//   ),
//   QuranSongModel(
//     name: 'Al-Ma\'idah',
//     number: 5',
//     mp3Url: '$${AppConstants.quranRecitationUrl}005.mp3',
//     filePath: '',
//   ),
//   QuranSongModel(
//     name: 'Al-An\'am',
//     number: 6',
//     mp3Url: '$${AppConstants.quranRecitationUrl}006.mp3',
//     filePath: '',
//   ),
//   QuranSongModel(
//     name: 'Al-A\'raf',
//     number: 7',
//     mp3Url: '$${AppConstants.quranRecitationUrl}007.mp3',
//     filePath: '',
//   ),
//   QuranSongModel(
//     name: 'Al-Anfal',
//     number: 8',
//     mp3Url: '$${AppConstants.quranRecitationUrl}008.mp3',
//     filePath: '',
//   ),
//   QuranSongModel(
//     name: 'At-Tawbah',
//     number: 9',
//     mp3Url: '$${AppConstants.quranRecitationUrl}009.mp3',
//     filePath: '',
//   ),
//   QuranSongModel(
//     name: 'Yunus',
//     number: 10',
//     mp3Url: '$${AppConstants.quranRecitationUrl}010.mp3',
//     filePath: '',
//   ),
//   QuranSongModel(
//     name: 'Ad-Duhaa',
//     number: 93',
//     mp3Url: '$${AppConstants.quranRecitationUrl}093.mp3',
//     filePath: 'Ad-Duhaa.mp3',
//   ),
// ];


final List<QuranSongModel> surahList = const [
  QuranSongModel(
    name: 'Al-Fatiha',
    number: 1,
    mp3Url: '${AppConstants.quranRecitationUrl}001.mp3',
    filePath: 'Al-Fatiha.mp3',
  ),
  QuranSongModel(
    name: 'Al-Baqarah',
    number: 2,
    mp3Url: '${AppConstants.quranRecitationUrl}002.mp3',
    filePath: 'Al-Baqarah.mp3',
  ),
  QuranSongModel(
    name: 'Al-Imran',
    number: 3,
    mp3Url: '${AppConstants.quranRecitationUrl}003.mp3',
    filePath: 'Al-Imran.mp3',
  ),
  QuranSongModel(
    name: 'An-Nisa',
    number: 4,
    mp3Url: '${AppConstants.quranRecitationUrl}004.mp3',
    filePath: 'An-Nisa.mp3',
  ),
  QuranSongModel(
    name: 'Al-Ma\'idah',
    number: 5,
    mp3Url: '${AppConstants.quranRecitationUrl}005.mp3',
    filePath: 'Al-Ma\'idah.mp3',
  ),
  QuranSongModel(
    name: 'Al-An\'am',
    number: 6,
    mp3Url: '${AppConstants.quranRecitationUrl}006.mp3',
    filePath: 'Al-An\'am.mp3',
  ),
  QuranSongModel(
    name: 'Al-A\'raf',
    number: 7,
    mp3Url: '${AppConstants.quranRecitationUrl}007.mp3',
    filePath: 'Al-A\'raf.mp3',
  ),
  QuranSongModel(
    name: 'Al-Anfal',
    number: 8,
    mp3Url: '${AppConstants.quranRecitationUrl}008.mp3',
    filePath: 'Al-Anfal.mp3',
  ),
  QuranSongModel(
    name: 'At-Tawbah',
    number: 9,
    mp3Url: '${AppConstants.quranRecitationUrl}009.mp3',
    filePath: 'Al-Tawbah.mp3',
  ),
  QuranSongModel(
    name: 'Yunus',
    number: 10,
    mp3Url: '${AppConstants.quranRecitationUrl}010.mp3',
    filePath: 'Yunus.mp3',
  ),
  QuranSongModel(
    name: 'Hud',
    number: 11,
    mp3Url: '${AppConstants.quranRecitationUrl}011.mp3',
    filePath: 'Hud.mp3',
  ),
  QuranSongModel(
    name: 'Yusuf',
    number: 12,
    mp3Url: '${AppConstants.quranRecitationUrl}012.mp3',
    filePath: 'Yusuf.mp3',
  ),
  QuranSongModel(
    name: 'Ar-Ra\'d',
    number: 13,
    mp3Url: '${AppConstants.quranRecitationUrl}013.mp3',
    filePath: 'Ar-Ra\'d.mp3',
  ),
  QuranSongModel(
    name: 'Ibrahim',
    number: 14,
    mp3Url: '${AppConstants.quranRecitationUrl}014.mp3',
    filePath: 'Ibrahim.mp3',
  ),
  QuranSongModel(
    name: 'Al-Hijr',
    number: 15,
    mp3Url: '${AppConstants.quranRecitationUrl}015.mp3',
    filePath: 'Al-Hijr.mp3',
  ),
  QuranSongModel(
    name: 'An-Nahl',
    number: 16,
    mp3Url: '${AppConstants.quranRecitationUrl}016.mp3',
    filePath: 'An-Nahl.mp3',
  ),
  QuranSongModel(
    name: 'Al-Isra',
    number: 17,
    mp3Url: '${AppConstants.quranRecitationUrl}017.mp3',
    filePath: 'Al-Isra.mp3',
  ),
  QuranSongModel(
    name: 'Al-Kahf',
    number: 18,
    mp3Url: '${AppConstants.quranRecitationUrl}018.mp3',
    filePath: 'Al-Kahf.mp3',
  ),
  QuranSongModel(
    name: 'Maryam',
    number: 19,
    mp3Url: '${AppConstants.quranRecitationUrl}019.mp3',
    filePath: 'Maryam.mp3',
  ),
  QuranSongModel(
    name: 'Ta-Ha',
    number: 20,
    mp3Url: '${AppConstants.quranRecitationUrl}020.mp3',
    filePath: 'Ta-Ha.mp3',
  ),
  QuranSongModel(
    name: 'Al-Anbiya',
    number: 21,
    mp3Url: '${AppConstants.quranRecitationUrl}021.mp3',
    filePath: 'Al-Anbiya.mp3',
  ),
  QuranSongModel(
    name: 'Al-Hajj',
    number: 22,
    mp3Url: '${AppConstants.quranRecitationUrl}022.mp3',
    filePath: 'Al-Hajj.mp3',
  ),
  QuranSongModel(
    name: 'Al-Mu\'minun',
    number: 23,
    mp3Url: '${AppConstants.quranRecitationUrl}023.mp3',
    filePath: 'Al-Mu\'minun.mp3',
  ),
  QuranSongModel(
    name: 'An-Nur',
    number: 24,
    mp3Url: '${AppConstants.quranRecitationUrl}024.mp3',
    filePath: 'An-Nur.mp3',
  ),
  QuranSongModel(
    name: 'Al-Furqan',
    number: 25,
    mp3Url: '${AppConstants.quranRecitationUrl}025.mp3',
    filePath: 'Al-Furqan.mp3',
  ),
  QuranSongModel(
    name: 'Ash-Shu\'ara',
    number: 26,
    mp3Url: '${AppConstants.quranRecitationUrl}026.mp3',
    filePath: 'Ash-Shu\'ara.mp3',
  ),
  QuranSongModel(
    name: 'An-Naml',
    number: 27,
    mp3Url: '${AppConstants.quranRecitationUrl}027.mp3',
    filePath: 'An-Naml.mp3',
  ),
  QuranSongModel(
    name: 'Al-Qasas',
    number: 28,
    mp3Url: '${AppConstants.quranRecitationUrl}028.mp3',
    filePath: 'Al-Qasas.mp3',
  ),
  QuranSongModel(
    name: 'Al-Ankabut',
    number: 29,
    mp3Url: '${AppConstants.quranRecitationUrl}029.mp3',
    filePath: 'Al-Ankabut.mp3',
  ),
  QuranSongModel(
    name: 'Ar-Rum',
    number: 30,
    mp3Url: '${AppConstants.quranRecitationUrl}030.mp3',
    filePath: 'Ar-Rum.mp3',
  ),
  QuranSongModel(
    name: 'Luqman',
    number: 31,
    mp3Url: '${AppConstants.quranRecitationUrl}031.mp3',
    filePath: 'Luqman.mp3',
  ),
  QuranSongModel(
    name: 'As-Sajdah',
    number: 32,
    mp3Url: '${AppConstants.quranRecitationUrl}032.mp3',
    filePath: 'As-Sajdah.mp3',
  ),
  QuranSongModel(
    name: 'Al-Ahzab',
    number: 33,
    mp3Url: '${AppConstants.quranRecitationUrl}033.mp3',
    filePath: 'Al-Ahzab.mp3',
  ),
  QuranSongModel(
    name: 'Saba',
    number: 34,
    mp3Url: '${AppConstants.quranRecitationUrl}034.mp3',
    filePath: 'Saba.mp3',
  ),
  QuranSongModel(
    name: 'Fatir',
    number: 35,
    mp3Url: '${AppConstants.quranRecitationUrl}035.mp3',
    filePath: 'Fatir.mp3',
  ),
  QuranSongModel(
    name: 'Ya-Sin',
    number: 36,
    mp3Url: '${AppConstants.quranRecitationUrl}036.mp3',
    filePath: 'Ya-Sin.mp3',
  ),
  QuranSongModel(
    name: 'As-Saffat',
    number: 37,
    mp3Url: '${AppConstants.quranRecitationUrl}037.mp3',
    filePath: 'As-Saffat.mp3',
  ),
  QuranSongModel(
    name: 'Sad',
    number: 38,
    mp3Url: '${AppConstants.quranRecitationUrl}038.mp3',
    filePath: 'Sad.mp3',
  ),
  QuranSongModel(
    name: 'Az-Zumar',
    number: 39,
    mp3Url: '${AppConstants.quranRecitationUrl}039.mp3',
    filePath: 'Az-Zumar.mp3',
  ),
  QuranSongModel(
    name: 'Ghafir',
    number: 40,
    mp3Url: '${AppConstants.quranRecitationUrl}040.mp3',
    filePath: 'Ghafir.mp3',
  ),
  QuranSongModel(
    name: 'Fussilat',
    number: 41,
    mp3Url: '${AppConstants.quranRecitationUrl}041.mp3',
    filePath: 'Fussilat.mp3',
  ),
  QuranSongModel(
    name: 'Ash-Shura',
    number: 42,
    mp3Url: '${AppConstants.quranRecitationUrl}042.mp3',
    filePath: 'Ash-Shura.mp3',
  ),
  QuranSongModel(
    name: 'Az-Zukhruf',
    number: 43,
    mp3Url: '${AppConstants.quranRecitationUrl}043.mp3',
    filePath: 'Az-Zukhruf.mp3',
  ),
  QuranSongModel(
    name: 'Ad-Dukhan',
    number: 44,
    mp3Url: '${AppConstants.quranRecitationUrl}044.mp3',
    filePath: 'Ad-Dukhan.mp3',
  ),
  QuranSongModel(
    name: 'Al-Jathiyah',
    number: 45,
    mp3Url: '${AppConstants.quranRecitationUrl}045.mp3',
    filePath: 'Al-Jathiyah.mp3',
  ),
  QuranSongModel(
    name: 'Al-Ahqaf',
    number: 46,
    mp3Url: '${AppConstants.quranRecitationUrl}046.mp3',
    filePath: 'Al-Ahqaf.mp3',
  ),
  QuranSongModel(
    name: 'Muhammad',
    number: 47,
    mp3Url: '${AppConstants.quranRecitationUrl}047.mp3',
    filePath: 'Muhammad.mp3',
  ),
  QuranSongModel(
    name: 'Al-Fath',
    number: 48,
    mp3Url: '${AppConstants.quranRecitationUrl}048.mp3',
    filePath: 'Al-Fath.mp3',
  ),
  QuranSongModel(
    name: 'Al-Hujurat',
    number: 49,
    mp3Url: '${AppConstants.quranRecitationUrl}049.mp3',
    filePath: 'Al-Hujurat.mp3',
  ),
  QuranSongModel(
    name: 'Qaf',
    number: 50,
    mp3Url: '${AppConstants.quranRecitationUrl}050.mp3',
    filePath: 'Qaf.mp3',
  ),
  QuranSongModel(
    name: 'Adh-Dhariyat',
    number: 51,
    mp3Url: '${AppConstants.quranRecitationUrl}051.mp3',
    filePath: 'Adh-Dhariyat.mp3',
  ),
  QuranSongModel(
    name: 'At-Tur',
    number: 52,
    mp3Url: '${AppConstants.quranRecitationUrl}052.mp3',
    filePath: 'At-Tur.mp3',
  ),
  QuranSongModel(
    name: 'An-Najm',
    number: 53,
    mp3Url: '${AppConstants.quranRecitationUrl}053.mp3',
    filePath: 'An-Najm.mp3',
  ),
  QuranSongModel(
    name: 'Al-Qamar',
    number: 54,
    mp3Url: '${AppConstants.quranRecitationUrl}054.mp3',
    filePath: 'Al-Qamar.mp3',
  ),
  QuranSongModel(
    name: 'Ar-Rahman',
    number: 55,
    mp3Url: '${AppConstants.quranRecitationUrl}055.mp3',
    filePath: 'Ar-Rahman.mp3',
  ),
  QuranSongModel(
    name: 'Al-Waqi\'ah',
    number: 56,
    mp3Url: '${AppConstants.quranRecitationUrl}056.mp3',
    filePath: 'Al-Waqi\'ah.mp3',
  ),
  QuranSongModel(
    name: 'Al-Hadid',
    number: 57,
    mp3Url: '${AppConstants.quranRecitationUrl}057.mp3',
    filePath: 'Al-Hadid.mp3',
  ),
  QuranSongModel(
    name: 'Al-Mujadila',
    number: 58,
    mp3Url: '${AppConstants.quranRecitationUrl}058.mp3',
    filePath: 'Al-Mujadila.mp3',
  ),
  QuranSongModel(
    name: 'Al-Hashr',
    number: 59,
    mp3Url: '${AppConstants.quranRecitationUrl}059.mp3',
    filePath: 'Al-Hashr.mp3',
  ),
  QuranSongModel(
    name: 'Al-Mumtahanah',
    number: 60,
    mp3Url: '${AppConstants.quranRecitationUrl}060.mp3',
    filePath: 'Al-Mumtahanah.mp3',
  ),
  QuranSongModel(
    name: 'As-Saff',
    number: 61,
    mp3Url: '${AppConstants.quranRecitationUrl}061.mp3',
    filePath: 'As-Saff.mp3',
  ),
  QuranSongModel(
    name: 'Al-Jumu\'ah',
    number: 62,
    mp3Url: '${AppConstants.quranRecitationUrl}062.mp3',
    filePath: 'Al-Jumu\'ah.mp3',
  ),
  QuranSongModel(
    name: 'Al-Munafiqun',
    number: 63,
    mp3Url: '${AppConstants.quranRecitationUrl}063.mp3',
    filePath: 'Al-Munafiqun.mp3',
  ),
  QuranSongModel(
    name: 'At-Taghabun',
    number: 64,
    mp3Url: '${AppConstants.quranRecitationUrl}064.mp3',
    filePath: 'At-Taghabun.mp3',
  ),
  QuranSongModel(
    name: 'At-Talaq',
    number: 65,
    mp3Url: '${AppConstants.quranRecitationUrl}065.mp3',
    filePath: 'At-Talaq.mp3',
  ),
  QuranSongModel(
    name: 'At-Tahrim',
    number: 66,
    mp3Url: '${AppConstants.quranRecitationUrl}066.mp3',
    filePath: 'At-Tahrim.mp3',
  ),
  QuranSongModel(
    name: 'Al-Mulk',
    number: 67,
    mp3Url: '${AppConstants.quranRecitationUrl}067.mp3',
    filePath: 'Al-Mulk.mp3',
  ),
  QuranSongModel(
    name: 'Al-Qalam',
    number: 68,
    mp3Url: '${AppConstants.quranRecitationUrl}068.mp3',
    filePath: 'Al-Qalam.mp3',
  ),
  QuranSongModel(
    name: 'Al-Haqqah',
    number: 69,
    mp3Url: '${AppConstants.quranRecitationUrl}069.mp3',
    filePath: 'Al-Haqqah.mp3',
  ),
  QuranSongModel(
    name: 'Al-Ma\'arij',
    number: 70,
    mp3Url: '${AppConstants.quranRecitationUrl}070.mp3',
    filePath: 'Al-Ma\'arij.mp3',
  ),
  QuranSongModel(
    name: 'Nuh',
    number: 71,
    mp3Url: '${AppConstants.quranRecitationUrl}071.mp3',
    filePath: 'Nuh.mp3',
  ),
  QuranSongModel(
    name: 'Al-Jinn',
    number: 72,
    mp3Url: '${AppConstants.quranRecitationUrl}072.mp3',
    filePath: 'Al-Jinn.mp3',
  ),
  QuranSongModel(
    name: 'Al-Muzzammil',
    number: 73,
    mp3Url: '${AppConstants.quranRecitationUrl}073.mp3',
    filePath: 'Al-Muzzammil,mp3',
  ),
  QuranSongModel(
    name: 'Al-Muddaththir',
    number: 74,
    mp3Url: '${AppConstants.quranRecitationUrl}074.mp3',
    filePath: 'Al-Muddaththir.mp3',
  ),
  QuranSongModel(
    name: 'Al-Qiyamah',
    number: 75,
    mp3Url: '${AppConstants.quranRecitationUrl}075.mp3',
    filePath: 'Al-Qiyamah.mp3',
  ),
  QuranSongModel(
    name: 'Al-Insan',
    number: 76,
    mp3Url: '${AppConstants.quranRecitationUrl}076.mp3',
    filePath: 'Al-Insan.mp3',
  ),
  QuranSongModel(
    name: 'Al-Mursalat',
    number: 77,
    mp3Url: '${AppConstants.quranRecitationUrl}077.mp3',
    filePath: 'Al-Mursalat.mp3',
  ),
  QuranSongModel(
    name: 'An-Naba',
    number: 78,
    mp3Url: '${AppConstants.quranRecitationUrl}078.mp3',
    filePath: 'An-Naba.mp3',
  ),
  QuranSongModel(
    name: 'An-Nazi\'at',
    number: 79,
    mp3Url: '${AppConstants.quranRecitationUrl}079.mp3',
    filePath: 'An-Nazi\'at.mp3',
  ),
  QuranSongModel(
    name: 'Abasa',
    number: 80,
    mp3Url: '${AppConstants.quranRecitationUrl}080.mp3',
    filePath: 'Abasa.mp3',
  ),
  QuranSongModel(
    name: 'At-Takwir',
    number: 81,
    mp3Url: '${AppConstants.quranRecitationUrl}081.mp3',
    filePath: 'At-Takwir.mp3',
  ),
  QuranSongModel(
    name: 'Al-Infitar',
    number: 82,
    mp3Url: '${AppConstants.quranRecitationUrl}082.mp3',
    filePath: 'Al-Infitar.mp3',
  ),
  QuranSongModel(
    name: 'Al-Mutaffifin',
    number: 83,
    mp3Url: '${AppConstants.quranRecitationUrl}083.mp3',
    filePath: 'Al-Mutaffifin.mp3',
  ),
  QuranSongModel(
    name: 'Al-Inshiqaq',
    number: 84,
    mp3Url: '${AppConstants.quranRecitationUrl}084.mp3',
    filePath: 'Al-Inshiqaq.mp3',
  ),
  QuranSongModel(
    name: 'Al-Buruj',
    number: 85,
    mp3Url: '${AppConstants.quranRecitationUrl}085.mp3',
    filePath: 'Al-Buruj.mp3',
  ),
  QuranSongModel(
    name: 'At-Tariq',
    number: 86,
    mp3Url: '${AppConstants.quranRecitationUrl}086.mp3',
    filePath: 'At-Tariq.mp3',
  ),
  QuranSongModel(
    name: 'Al-A\'la',
    number: 87,
    mp3Url: '${AppConstants.quranRecitationUrl}087.mp3',
    filePath: 'Al-A\'la.mp3',
  ),
  QuranSongModel(
    name: 'Al-Ghashiyah',
    number: 88,
    mp3Url: '${AppConstants.quranRecitationUrl}088.mp3',
    filePath: 'Al-Ghashiyah.mp3',
  ),
  QuranSongModel(
    name: 'Al-Fajr',
    number: 89,
    mp3Url: '${AppConstants.quranRecitationUrl}089.mp3',
    filePath: 'Al-Fajr.mp3',
  ),
  QuranSongModel(
    name: 'Al-Balad',
    number: 90,
    mp3Url: '${AppConstants.quranRecitationUrl}090.mp3',
    filePath: 'Al-Balad.mp3',
  ),
  QuranSongModel(
    name: 'Ash-Shams',
    number: 91,
    mp3Url: '${AppConstants.quranRecitationUrl}091.mp3',
    filePath: 'Ash-Shams.mp3',
  ),
  QuranSongModel(
    name: 'Al-Layl',
    number: 92,
    mp3Url: '${AppConstants.quranRecitationUrl}092.mp3',
    filePath: 'Al-Layl.mp3',
  ),
  QuranSongModel(
    name: 'Ad-Duhaa',
    number: 93,
    mp3Url: '${AppConstants.quranRecitationUrl}093.mp3',
    filePath: 'Ad-Duhaa.mp3',
  ),
  QuranSongModel(
    name: 'Ash-Sharh',
    number: 94,
    mp3Url: '${AppConstants.quranRecitationUrl}094.mp3',
    filePath: 'Ash-Sharh.mp3',
  ),
  QuranSongModel(
    name: 'At-Tin',
    number: 95,
    mp3Url: '${AppConstants.quranRecitationUrl}095.mp3',
    filePath: 'At-Tin.mp3',
  ),
  QuranSongModel(
    name: 'Al-Alaq',
    number: 96,
    mp3Url: '${AppConstants.quranRecitationUrl}096.mp3',
    filePath: 'Al-Alaq.mp3',
  ),
  QuranSongModel(
    name: 'Al-Qadr',
    number: 97,
    mp3Url: '${AppConstants.quranRecitationUrl}097.mp3',
    filePath: 'Al-Qadr.mp3',
  ),
  QuranSongModel(
    name: 'Al-Bayyinah',
    number: 98,
    mp3Url: '${AppConstants.quranRecitationUrl}098.mp3',
    filePath: 'Al-Bayyinah.mp3',
  ),
  QuranSongModel(
    name: 'Az-Zalzalah',
    number: 99,
    mp3Url: '${AppConstants.quranRecitationUrl}099.mp3',
    filePath: 'Az-Zalzalah.mp3',
  ),
  QuranSongModel(
    name: 'Al-Adiyat',
    number: 100,
    mp3Url: '${AppConstants.quranRecitationUrl}100.mp3',
    filePath: 'Al-Adiyat.mp3',
  ),
  QuranSongModel(
    name: 'Al-Qari\'ah',
    number: 101,
    mp3Url: '${AppConstants.quranRecitationUrl}101.mp3',
    filePath: 'Al-Qari\'ah.mp3',
  ),
  QuranSongModel(
    name: 'At-Takathur',
    number: 102,
    mp3Url: '${AppConstants.quranRecitationUrl}102.mp3',
    filePath: 'At-Takathur.mp3',
  ),
  QuranSongModel(
    name: 'Al-Asr',
    number: 103,
    mp3Url: '${AppConstants.quranRecitationUrl}103.mp3',
    filePath: 'Al-Asr.mp3',
  ),
  QuranSongModel(
    name: 'Al-Humazah',
    number: 104,
    mp3Url: '${AppConstants.quranRecitationUrl}104.mp3',
    filePath: 'Al-Humazah.mp3',
  ),
  QuranSongModel(
    name: 'Al-Fil',
    number: 105,
    mp3Url: '${AppConstants.quranRecitationUrl}105.mp3',
    filePath: 'Al-Fil.mp3',
  ),
  QuranSongModel(
    name: 'Quraysh',
    number: 106,
    mp3Url: '${AppConstants.quranRecitationUrl}106.mp3',
    filePath: 'Quraysh.mp3',
  ),
  QuranSongModel(
    name: 'Al-Ma\'un',
    number: 107,
    mp3Url: '${AppConstants.quranRecitationUrl}107.mp3',
    filePath: 'Al-Ma\'un.mp3',
  ),
  QuranSongModel(
    name: 'Al-Kawthar',
    number: 108,
    mp3Url: '${AppConstants.quranRecitationUrl}108.mp3',
    filePath: 'Al-Kawthar.mp3',
  ),
  QuranSongModel(
    name: 'Al-Kafirun',
    number: 109,
    mp3Url: '${AppConstants.quranRecitationUrl}109.mp3',
    filePath: 'Al-Kafirun.mp3',
  ),
  QuranSongModel(
    name: 'An-Nasr',
    number: 110,
    mp3Url: '${AppConstants.quranRecitationUrl}110.mp3',
    filePath: 'An-Nasr.mp3',
  ),
  QuranSongModel(
    name: 'Al-Masad',
    number: 111,
    mp3Url: '${AppConstants.quranRecitationUrl}111.mp3',
    filePath: 'Al-Masad.mp3',
  ),
  QuranSongModel(
    name: 'Al-Ikhlas',
    number: 112,
    mp3Url: '${AppConstants.quranRecitationUrl}112.mp3',
    filePath: 'Al-Ikhlas.mp3',
  ),
  QuranSongModel(
    name: 'Al-Falaq',
    number: 113,
    mp3Url: '${AppConstants.quranRecitationUrl}113.mp3',
    filePath: 'Al-Falaq.mp3',
  ),
  QuranSongModel(
    name: 'An-Nas',
    number: 114,
    mp3Url: '${AppConstants.quranRecitationUrl}114.mp3',
    filePath: 'An-Nas.mp3',
  ),
];

